on:
  push:
    branches:
      - main

jobs:
  wordpress-wpscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start WordPress Environment
        env:
          # added as vars cuz its testing env
          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
          WORDPRESS_DB_PASSWORD: ${{ vars.WORDPRESS_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
          MYSQL_USER: ${{ vars.MYSQL_USER }}
          WORDPRESS_DB_HOST: ${{ vars.WORDPRESS_DB_HOST }}
          WORDPRESS_DB_USER: ${{ vars.WORDPRESS_DB_USER }}
          WORDPRESS_DB_NAME: ${{ vars.WORDPRESS_DB_NAME }}
        run: |
          docker compose up -d

      - name: Wait for WordPress to be ready
        run: |
          echo "Waiting for WordPress to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/wp-content/ | grep -q "<title>"; then
              echo "WordPress is ready!"
              break
            fi
            sleep 5
          done

      - name: Complete WordPress Installation via WP-CLI
        run: |
          docker run --rm --network host wordpress:cli wp core install \
            --path="/var/www/html" \
            --url="http://localhost:8080" \
            --title="WPScan Test Site" \
            --admin_user="admin" \
            --admin_password="TestingPassword123!" \
            --admin_email="test@example.com" \
            --skip-email

      - name: Run WPScan via Docker
        run: |
          docker run --rm --network host wpscanteam/wpscan \
            --url http://localhost:8080 \
            --enumerate u,vp,vt \
            --clear-cache \
            --api-token ${{ secrets.WPSCAN_API_TOKEN }} \
            --force | tee scans/wpscan-artifact.txt || true
